In [14]:
data = open("ex1data1.txt", "r")

In [2]:
import numpy as np

In [15]:
values = data.read()

In [16]:
values

'6.1101,17.592\n5.5277,9.1302\n8.5186,13.662\n7.0032,11.854\n5.8598,6.8233\n8.3829,11.886\n7.4764,4.3483\n8.5781,12\n6.4862,6.5987\n5.0546,3.8166\n5.7107,3.2522\n14.164,15.505\n5.734,3.1551\n8.4084,7.2258\n5.6407,0.71618\n5.3794,3.5129\n6.3654,5.3048\n5.1301,0.56077\n6.4296,3.6518\n7.0708,5.3893\n6.1891,3.1386\n20.27,21.767\n5.4901,4.263\n6.3261,5.1875\n5.5649,3.0825\n18.945,22.638\n12.828,13.501\n10.957,7.0467\n13.176,14.692\n22.203,24.147\n5.2524,-1.22\n6.5894,5.9966\n9.2482,12.134\n5.8918,1.8495\n8.2111,6.5426\n7.9334,4.5623\n8.0959,4.1164\n5.6063,3.3928\n12.836,10.117\n6.3534,5.4974\n5.4069,0.55657\n6.8825,3.9115\n11.708,5.3854\n5.7737,2.4406\n7.8247,6.7318\n7.0931,1.0463\n5.0702,5.1337\n5.8014,1.844\n11.7,8.0043\n5.5416,1.0179\n7.5402,6.7504\n5.3077,1.8396\n7.4239,4.2885\n7.6031,4.9981\n6.3328,1.4233\n6.3589,-1.4211\n6.2742,2.4756\n5.6397,4.6042\n9.3102,3.9624\n9.4536,5.4141\n8.8254,5.1694\n5.1793,-0.74279\n21.279,17.929\n14.908,12.054\n18.959,17.054\n7.2182,4.8852\n8.2951,5.7442\

In [17]:
values.strip("\n")

'6.1101,17.592\n5.5277,9.1302\n8.5186,13.662\n7.0032,11.854\n5.8598,6.8233\n8.3829,11.886\n7.4764,4.3483\n8.5781,12\n6.4862,6.5987\n5.0546,3.8166\n5.7107,3.2522\n14.164,15.505\n5.734,3.1551\n8.4084,7.2258\n5.6407,0.71618\n5.3794,3.5129\n6.3654,5.3048\n5.1301,0.56077\n6.4296,3.6518\n7.0708,5.3893\n6.1891,3.1386\n20.27,21.767\n5.4901,4.263\n6.3261,5.1875\n5.5649,3.0825\n18.945,22.638\n12.828,13.501\n10.957,7.0467\n13.176,14.692\n22.203,24.147\n5.2524,-1.22\n6.5894,5.9966\n9.2482,12.134\n5.8918,1.8495\n8.2111,6.5426\n7.9334,4.5623\n8.0959,4.1164\n5.6063,3.3928\n12.836,10.117\n6.3534,5.4974\n5.4069,0.55657\n6.8825,3.9115\n11.708,5.3854\n5.7737,2.4406\n7.8247,6.7318\n7.0931,1.0463\n5.0702,5.1337\n5.8014,1.844\n11.7,8.0043\n5.5416,1.0179\n7.5402,6.7504\n5.3077,1.8396\n7.4239,4.2885\n7.6031,4.9981\n6.3328,1.4233\n6.3589,-1.4211\n6.2742,2.4756\n5.6397,4.6042\n9.3102,3.9624\n9.4536,5.4141\n8.8254,5.1694\n5.1793,-0.74279\n21.279,17.929\n14.908,12.054\n18.959,17.054\n7.2182,4.8852\n8.2951,5.7442\

In [18]:
values = values.strip("\n")

In [19]:
values

'6.1101,17.592\n5.5277,9.1302\n8.5186,13.662\n7.0032,11.854\n5.8598,6.8233\n8.3829,11.886\n7.4764,4.3483\n8.5781,12\n6.4862,6.5987\n5.0546,3.8166\n5.7107,3.2522\n14.164,15.505\n5.734,3.1551\n8.4084,7.2258\n5.6407,0.71618\n5.3794,3.5129\n6.3654,5.3048\n5.1301,0.56077\n6.4296,3.6518\n7.0708,5.3893\n6.1891,3.1386\n20.27,21.767\n5.4901,4.263\n6.3261,5.1875\n5.5649,3.0825\n18.945,22.638\n12.828,13.501\n10.957,7.0467\n13.176,14.692\n22.203,24.147\n5.2524,-1.22\n6.5894,5.9966\n9.2482,12.134\n5.8918,1.8495\n8.2111,6.5426\n7.9334,4.5623\n8.0959,4.1164\n5.6063,3.3928\n12.836,10.117\n6.3534,5.4974\n5.4069,0.55657\n6.8825,3.9115\n11.708,5.3854\n5.7737,2.4406\n7.8247,6.7318\n7.0931,1.0463\n5.0702,5.1337\n5.8014,1.844\n11.7,8.0043\n5.5416,1.0179\n7.5402,6.7504\n5.3077,1.8396\n7.4239,4.2885\n7.6031,4.9981\n6.3328,1.4233\n6.3589,-1.4211\n6.2742,2.4756\n5.6397,4.6042\n9.3102,3.9624\n9.4536,5.4141\n8.8254,5.1694\n5.1793,-0.74279\n21.279,17.929\n14.908,12.054\n18.959,17.054\n7.2182,4.8852\n8.2951,5.7442\

In [24]:
number = values.split("\n")

In [25]:
number

['6.1101,17.592',
 '5.5277,9.1302',
 '8.5186,13.662',
 '7.0032,11.854',
 '5.8598,6.8233',
 '8.3829,11.886',
 '7.4764,4.3483',
 '8.5781,12',
 '6.4862,6.5987',
 '5.0546,3.8166',
 '5.7107,3.2522',
 '14.164,15.505',
 '5.734,3.1551',
 '8.4084,7.2258',
 '5.6407,0.71618',
 '5.3794,3.5129',
 '6.3654,5.3048',
 '5.1301,0.56077',
 '6.4296,3.6518',
 '7.0708,5.3893',
 '6.1891,3.1386',
 '20.27,21.767',
 '5.4901,4.263',
 '6.3261,5.1875',
 '5.5649,3.0825',
 '18.945,22.638',
 '12.828,13.501',
 '10.957,7.0467',
 '13.176,14.692',
 '22.203,24.147',
 '5.2524,-1.22',
 '6.5894,5.9966',
 '9.2482,12.134',
 '5.8918,1.8495',
 '8.2111,6.5426',
 '7.9334,4.5623',
 '8.0959,4.1164',
 '5.6063,3.3928',
 '12.836,10.117',
 '6.3534,5.4974',
 '5.4069,0.55657',
 '6.8825,3.9115',
 '11.708,5.3854',
 '5.7737,2.4406',
 '7.8247,6.7318',
 '7.0931,1.0463',
 '5.0702,5.1337',
 '5.8014,1.844',
 '11.7,8.0043',
 '5.5416,1.0179',
 '7.5402,6.7504',
 '5.3077,1.8396',
 '7.4239,4.2885',
 '7.6031,4.9981',
 '6.3328,1.4233',
 '6.3589,-1.4211',

In [46]:
X = []

In [47]:
Y = []

In [29]:
X

[]

In [48]:
for k in number:
    X.append(float(k.split(',')[0]))
    Y.append(float(k.split(',')[1]))

In [199]:
number = ''.join(number)


In [200]:
number

'6.1101,17.5925.5277,9.13028.5186,13.6627.0032,11.8545.8598,6.82338.3829,11.8867.4764,4.34838.5781,126.4862,6.59875.0546,3.81665.7107,3.252214.164,15.5055.734,3.15518.4084,7.22585.6407,0.716185.3794,3.51296.3654,5.30485.1301,0.560776.4296,3.65187.0708,5.38936.1891,3.138620.27,21.7675.4901,4.2636.3261,5.18755.5649,3.082518.945,22.63812.828,13.50110.957,7.046713.176,14.69222.203,24.1475.2524,-1.226.5894,5.99669.2482,12.1345.8918,1.84958.2111,6.54267.9334,4.56238.0959,4.11645.6063,3.392812.836,10.1176.3534,5.49745.4069,0.556576.8825,3.911511.708,5.38545.7737,2.44067.8247,6.73187.0931,1.04635.0702,5.13375.8014,1.84411.7,8.00435.5416,1.01797.5402,6.75045.3077,1.83967.4239,4.28857.6031,4.99816.3328,1.42336.3589,-1.42116.2742,2.47565.6397,4.60429.3102,3.96249.4536,5.41418.8254,5.16945.1793,-0.7427921.279,17.92914.908,12.05418.959,17.0547.2182,4.88528.2951,5.744210.236,7.77545.4994,1.017320.341,20.99210.136,6.67997.3345,4.02596.0062,1.27847.2259,3.34115.0269,-2.68076.5479,0.296787.5386,3.88455

In [68]:
mtr_X = np.matrix(X)

In [69]:
mtr_X 

matrix([[  6.1101,   5.5277,   8.5186,   7.0032,   5.8598,   8.3829,
           7.4764,   8.5781,   6.4862,   5.0546,   5.7107,  14.164 ,
           5.734 ,   8.4084,   5.6407,   5.3794,   6.3654,   5.1301,
           6.4296,   7.0708,   6.1891,  20.27  ,   5.4901,   6.3261,
           5.5649,  18.945 ,  12.828 ,  10.957 ,  13.176 ,  22.203 ,
           5.2524,   6.5894,   9.2482,   5.8918,   8.2111,   7.9334,
           8.0959,   5.6063,  12.836 ,   6.3534,   5.4069,   6.8825,
          11.708 ,   5.7737,   7.8247,   7.0931,   5.0702,   5.8014,
          11.7   ,   5.5416,   7.5402,   5.3077,   7.4239,   7.6031,
           6.3328,   6.3589,   6.2742,   5.6397,   9.3102,   9.4536,
           8.8254,   5.1793,  21.279 ,  14.908 ,  18.959 ,   7.2182,
           8.2951,  10.236 ,   5.4994,  20.341 ,  10.136 ,   7.3345,
           6.0062,   7.2259,   5.0269,   6.5479,   7.5386,   5.0365,
          10.274 ,   5.1077,   5.7292,   5.1884,   6.3557,   9.7687,
           6.5159,   8.5172,   9.1

In [70]:
mtr_Y = np.matrix(Y)

In [71]:
mtr_Y

matrix([[ 17.592  ,   9.1302 ,  13.662  ,  11.854  ,   6.8233 ,  11.886  ,
           4.3483 ,  12.     ,   6.5987 ,   3.8166 ,   3.2522 ,  15.505  ,
           3.1551 ,   7.2258 ,   0.71618,   3.5129 ,   5.3048 ,   0.56077,
           3.6518 ,   5.3893 ,   3.1386 ,  21.767  ,   4.263  ,   5.1875 ,
           3.0825 ,  22.638  ,  13.501  ,   7.0467 ,  14.692  ,  24.147  ,
          -1.22   ,   5.9966 ,  12.134  ,   1.8495 ,   6.5426 ,   4.5623 ,
           4.1164 ,   3.3928 ,  10.117  ,   5.4974 ,   0.55657,   3.9115 ,
           5.3854 ,   2.4406 ,   6.7318 ,   1.0463 ,   5.1337 ,   1.844  ,
           8.0043 ,   1.0179 ,   6.7504 ,   1.8396 ,   4.2885 ,   4.9981 ,
           1.4233 ,  -1.4211 ,   2.4756 ,   4.6042 ,   3.9624 ,   5.4141 ,
           5.1694 ,  -0.74279,  17.929  ,  12.054  ,  17.054  ,   4.8852 ,
           5.7442 ,   7.7754 ,   1.0173 ,  20.992  ,   6.6799 ,   4.0259 ,
           1.2784 ,   3.3411 ,  -2.6807 ,   0.29678,   3.8845 ,   5.7014 ,
           6.7526 ,   2.0

In [72]:
mtr_X

matrix([[  6.1101,   5.5277,   8.5186,   7.0032,   5.8598,   8.3829,
           7.4764,   8.5781,   6.4862,   5.0546,   5.7107,  14.164 ,
           5.734 ,   8.4084,   5.6407,   5.3794,   6.3654,   5.1301,
           6.4296,   7.0708,   6.1891,  20.27  ,   5.4901,   6.3261,
           5.5649,  18.945 ,  12.828 ,  10.957 ,  13.176 ,  22.203 ,
           5.2524,   6.5894,   9.2482,   5.8918,   8.2111,   7.9334,
           8.0959,   5.6063,  12.836 ,   6.3534,   5.4069,   6.8825,
          11.708 ,   5.7737,   7.8247,   7.0931,   5.0702,   5.8014,
          11.7   ,   5.5416,   7.5402,   5.3077,   7.4239,   7.6031,
           6.3328,   6.3589,   6.2742,   5.6397,   9.3102,   9.4536,
           8.8254,   5.1793,  21.279 ,  14.908 ,  18.959 ,   7.2182,
           8.2951,  10.236 ,   5.4994,  20.341 ,  10.136 ,   7.3345,
           6.0062,   7.2259,   5.0269,   6.5479,   7.5386,   5.0365,
          10.274 ,   5.1077,   5.7292,   5.1884,   6.3557,   9.7687,
           6.5159,   8.5172,   9.1

In [76]:
ones = np.transpose(np.ones(mtr_X.shape))

In [77]:
ones

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [99]:
mtr_X_prime = np.r_[np.transpose(ones), mtr_X]

In [104]:
mtr_X = mtr_X.reshape(97,1)

In [106]:
mtr_X_prime = np.c_[ones, mtr_X]

In [107]:
mtr_X_prime

matrix([[  1.    ,   6.1101],
        [  1.    ,   5.5277],
        [  1.    ,   8.5186],
        [  1.    ,   7.0032],
        [  1.    ,   5.8598],
        [  1.    ,   8.3829],
        [  1.    ,   7.4764],
        [  1.    ,   8.5781],
        [  1.    ,   6.4862],
        [  1.    ,   5.0546],
        [  1.    ,   5.7107],
        [  1.    ,  14.164 ],
        [  1.    ,   5.734 ],
        [  1.    ,   8.4084],
        [  1.    ,   5.6407],
        [  1.    ,   5.3794],
        [  1.    ,   6.3654],
        [  1.    ,   5.1301],
        [  1.    ,   6.4296],
        [  1.    ,   7.0708],
        [  1.    ,   6.1891],
        [  1.    ,  20.27  ],
        [  1.    ,   5.4901],
        [  1.    ,   6.3261],
        [  1.    ,   5.5649],
        [  1.    ,  18.945 ],
        [  1.    ,  12.828 ],
        [  1.    ,  10.957 ],
        [  1.    ,  13.176 ],
        [  1.    ,  22.203 ],
        [  1.    ,   5.2524],
        [  1.    ,   6.5894],
        [  1.    ,   9.2482],
        [ 

In [109]:
theta = np.zeros(2)


In [110]:
theta

array([ 0.,  0.])

In [115]:
theta = theta.reshape(2,1)

In [122]:
mtr_Y.size

97

In [160]:
def costFunction(X,y, theta):
    m=y.size
    H = X*theta
    return ((1/(2*m))*np.transpose(H-y)*(H-y))[0,0]

In [130]:
H = mtr_X_prime*theta

In [132]:
H.shape

(97, 1)

In [134]:
mtr_Y = mtr_Y.reshape(97,1)

In [135]:
mtr_Y

matrix([[ 17.592  ],
        [  9.1302 ],
        [ 13.662  ],
        [ 11.854  ],
        [  6.8233 ],
        [ 11.886  ],
        [  4.3483 ],
        [ 12.     ],
        [  6.5987 ],
        [  3.8166 ],
        [  3.2522 ],
        [ 15.505  ],
        [  3.1551 ],
        [  7.2258 ],
        [  0.71618],
        [  3.5129 ],
        [  5.3048 ],
        [  0.56077],
        [  3.6518 ],
        [  5.3893 ],
        [  3.1386 ],
        [ 21.767  ],
        [  4.263  ],
        [  5.1875 ],
        [  3.0825 ],
        [ 22.638  ],
        [ 13.501  ],
        [  7.0467 ],
        [ 14.692  ],
        [ 24.147  ],
        [ -1.22   ],
        [  5.9966 ],
        [ 12.134  ],
        [  1.8495 ],
        [  6.5426 ],
        [  4.5623 ],
        [  4.1164 ],
        [  3.3928 ],
        [ 10.117  ],
        [  5.4974 ],
        [  0.55657],
        [  3.9115 ],
        [  5.3854 ],
        [  2.4406 ],
        [  6.7318 ],
        [  1.0463 ],
        [  5.1337 ],
        [  1.

In [161]:
costFunction(mtr_X_prime,mtr_Y,theta)

32.072733877455669

In [139]:
mtr_Y.size

97

In [140]:
x = mtr_X_prime

In [141]:
y = mtr_Y

In [142]:
H = x*theta - y 

In [144]:
p = np.transpose(H)*H

In [145]:
p

matrix([[ 6222.11037223]])

In [146]:
p/2*97

matrix([[ 301772.35305298]])

In [147]:
p.size

1

In [148]:
p

matrix([[ 6222.11037223]])

In [149]:
p[0]

matrix([[ 6222.11037223]])

In [150]:
p.shape

(1, 1)

In [153]:
p[0,0]/(2*97)

32.072733877455669

In [155]:
costFunction(x,y,theta)

matrix([[ 1.59524981,  0.8279303 ,  1.23887579,  1.07492561,  0.61873966,
          1.07782738,  0.39430564,  1.08816495,  0.59837284,  0.34609086,
          0.29491084,  1.40599979,  0.28610577,  0.65523852,  0.0649435 ,
          0.31855122,  0.48104145,  0.05085085,  0.33114673,  0.48870395,
          0.28460954,  1.97384054,  0.3865706 ,  0.47040464,  0.27952237,
          2.05282318,  1.22427625,  0.63899766,  1.33227662,  2.18965992,
         -0.1106301 ,  0.54377416,  1.10031612,  0.16771342,  0.59328567,
          0.41371125,  0.37327685,  0.3076605 ,  0.91741373,  0.4985065 ,
          0.05047   ,  0.35469643,  0.48835029,  0.22131461,  0.6104424 ,
          0.09487892,  0.46552603,  0.16721468,  0.72583322,  0.09230359,
          0.61212906,  0.16681569,  0.38888295,  0.45322977,  0.12906543,
         -0.12886593,  0.22448843,  0.41751075,  0.35931207,  0.49095282,
          0.46876332, -0.0673565 ,  1.62580911,  1.09306169,  1.54646375,
          0.44299195,  0.52088642,  0.

In [176]:
def gradientDescent(X, y, theta, iterr, alpha):
    const=alpha/y.size
    cost = []
    for i in range(iterr):
        theta_temp = theta.copy()
        theta_temp = theta_temp - const*(np.transpose(X)*(X*theta - y))
        theta = theta_temp
        cost.append(costFunction(X,y,theta))
    return (cost, theta)
        

In [167]:
cost, theta = gradientDescent(mtr_X_prime, mtr_Y, theta, 1500, 0.01)

/home/pedrobcst/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in subtract
  


In [177]:
theta = np.zeros(2).reshape(2,1)

In [170]:
theta

array([[ 0.],
       [ 0.]])

In [171]:
theta_temp = theta.copy()

In [178]:
cost = []

In [179]:
cost, theta = gradientDescent(mtr_X_prime, mtr_Y, theta, 1500, 0.01)

In [185]:
theta.shape

(2, 1)

In [186]:
theta[0,0]

-3.6302914394043602

In [187]:
theta[1,0]

1.166362350335582

In [201]:
number

'6.1101,17.5925.5277,9.13028.5186,13.6627.0032,11.8545.8598,6.82338.3829,11.8867.4764,4.34838.5781,126.4862,6.59875.0546,3.81665.7107,3.252214.164,15.5055.734,3.15518.4084,7.22585.6407,0.716185.3794,3.51296.3654,5.30485.1301,0.560776.4296,3.65187.0708,5.38936.1891,3.138620.27,21.7675.4901,4.2636.3261,5.18755.5649,3.082518.945,22.63812.828,13.50110.957,7.046713.176,14.69222.203,24.1475.2524,-1.226.5894,5.99669.2482,12.1345.8918,1.84958.2111,6.54267.9334,4.56238.0959,4.11645.6063,3.392812.836,10.1176.3534,5.49745.4069,0.556576.8825,3.911511.708,5.38545.7737,2.44067.8247,6.73187.0931,1.04635.0702,5.13375.8014,1.84411.7,8.00435.5416,1.01797.5402,6.75045.3077,1.83967.4239,4.28857.6031,4.99816.3328,1.42336.3589,-1.42116.2742,2.47565.6397,4.60429.3102,3.96249.4536,5.41418.8254,5.16945.1793,-0.7427921.279,17.92914.908,12.05418.959,17.0547.2182,4.88528.2951,5.744210.236,7.77545.4994,1.017320.341,20.99210.136,6.67997.3345,4.02596.0062,1.27847.2259,3.34115.0269,-2.68076.5479,0.296787.5386,3.88455

In [204]:
L = number.split(',')

In [206]:
L = data.read().split("\n")

In [209]:
with open("ex1data1.txt","r") as data:
    L = data.read().split("\n")

In [211]:
L = ','.join(L)

In [212]:
L

'6.1101,17.592,5.5277,9.1302,8.5186,13.662,7.0032,11.854,5.8598,6.8233,8.3829,11.886,7.4764,4.3483,8.5781,12,6.4862,6.5987,5.0546,3.8166,5.7107,3.2522,14.164,15.505,5.734,3.1551,8.4084,7.2258,5.6407,0.71618,5.3794,3.5129,6.3654,5.3048,5.1301,0.56077,6.4296,3.6518,7.0708,5.3893,6.1891,3.1386,20.27,21.767,5.4901,4.263,6.3261,5.1875,5.5649,3.0825,18.945,22.638,12.828,13.501,10.957,7.0467,13.176,14.692,22.203,24.147,5.2524,-1.22,6.5894,5.9966,9.2482,12.134,5.8918,1.8495,8.2111,6.5426,7.9334,4.5623,8.0959,4.1164,5.6063,3.3928,12.836,10.117,6.3534,5.4974,5.4069,0.55657,6.8825,3.9115,11.708,5.3854,5.7737,2.4406,7.8247,6.7318,7.0931,1.0463,5.0702,5.1337,5.8014,1.844,11.7,8.0043,5.5416,1.0179,7.5402,6.7504,5.3077,1.8396,7.4239,4.2885,7.6031,4.9981,6.3328,1.4233,6.3589,-1.4211,6.2742,2.4756,5.6397,4.6042,9.3102,3.9624,9.4536,5.4141,8.8254,5.1694,5.1793,-0.74279,21.279,17.929,14.908,12.054,18.959,17.054,7.2182,4.8852,8.2951,5.7442,10.236,7.7754,5.4994,1.0173,20.341,20.992,10.136,6.6799,7.3345,4.0

In [220]:
B = L.split(',')[::2]

In [221]:
B

['6.1101',
 '5.5277',
 '8.5186',
 '7.0032',
 '5.8598',
 '8.3829',
 '7.4764',
 '8.5781',
 '6.4862',
 '5.0546',
 '5.7107',
 '14.164',
 '5.734',
 '8.4084',
 '5.6407',
 '5.3794',
 '6.3654',
 '5.1301',
 '6.4296',
 '7.0708',
 '6.1891',
 '20.27',
 '5.4901',
 '6.3261',
 '5.5649',
 '18.945',
 '12.828',
 '10.957',
 '13.176',
 '22.203',
 '5.2524',
 '6.5894',
 '9.2482',
 '5.8918',
 '8.2111',
 '7.9334',
 '8.0959',
 '5.6063',
 '12.836',
 '6.3534',
 '5.4069',
 '6.8825',
 '11.708',
 '5.7737',
 '7.8247',
 '7.0931',
 '5.0702',
 '5.8014',
 '11.7',
 '5.5416',
 '7.5402',
 '5.3077',
 '7.4239',
 '7.6031',
 '6.3328',
 '6.3589',
 '6.2742',
 '5.6397',
 '9.3102',
 '9.4536',
 '8.8254',
 '5.1793',
 '21.279',
 '14.908',
 '18.959',
 '7.2182',
 '8.2951',
 '10.236',
 '5.4994',
 '20.341',
 '10.136',
 '7.3345',
 '6.0062',
 '7.2259',
 '5.0269',
 '6.5479',
 '7.5386',
 '5.0365',
 '10.274',
 '5.1077',
 '5.7292',
 '5.1884',
 '6.3557',
 '9.7687',
 '6.5159',
 '8.5172',
 '9.1802',
 '6.002',
 '5.5204',
 '5.0594',
 '5.7077',
 '7.

In [223]:
mm = map(lambda k:float(k), B)

In [226]:
for i in range(len(B)):
    B[i] = float(B[i])

ValueError: could not convert string to float: 

In [227]:
B

[6.1101,
 5.5277,
 8.5186,
 7.0032,
 5.8598,
 8.3829,
 7.4764,
 8.5781,
 6.4862,
 5.0546,
 5.7107,
 14.164,
 5.734,
 8.4084,
 5.6407,
 5.3794,
 6.3654,
 5.1301,
 6.4296,
 7.0708,
 6.1891,
 20.27,
 5.4901,
 6.3261,
 5.5649,
 18.945,
 12.828,
 10.957,
 13.176,
 22.203,
 5.2524,
 6.5894,
 9.2482,
 5.8918,
 8.2111,
 7.9334,
 8.0959,
 5.6063,
 12.836,
 6.3534,
 5.4069,
 6.8825,
 11.708,
 5.7737,
 7.8247,
 7.0931,
 5.0702,
 5.8014,
 11.7,
 5.5416,
 7.5402,
 5.3077,
 7.4239,
 7.6031,
 6.3328,
 6.3589,
 6.2742,
 5.6397,
 9.3102,
 9.4536,
 8.8254,
 5.1793,
 21.279,
 14.908,
 18.959,
 7.2182,
 8.2951,
 10.236,
 5.4994,
 20.341,
 10.136,
 7.3345,
 6.0062,
 7.2259,
 5.0269,
 6.5479,
 7.5386,
 5.0365,
 10.274,
 5.1077,
 5.7292,
 5.1884,
 6.3557,
 9.7687,
 6.5159,
 8.5172,
 9.1802,
 6.002,
 5.5204,
 5.0594,
 5.7077,
 7.6366,
 5.8707,
 5.3054,
 8.2934,
 13.394,
 5.4369,
 '']

In [229]:
del(B[-1])

In [231]:
B == X/

SyntaxError: invalid syntax (<ipython-input-231-a9893e83922f>, line 1)

In [232]:
B == X

True

In [233]:
np.zeros(500)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [234]:
Z = np.zeros(500)

In [235]:
for i in range(Z.size):
    Z[i] = 22

In [240]:
Z = Z.reshape(500,1)


In [241]:
Z.shape

(500, 1)

In [243]:
Z.reshape(500,).shape

(500,)

In [244]:
thetas = np.zeros(2).reshape(2,1)

In [245]:
thetas

array([[ 0.],
       [ 0.]])